[package]
name = "picrypt"
version ="0.1.1"
edition = "2021"
authors=["Dessxvii <anoncomrade993@gmail.com>"]



[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
[dependencies]
pixelate = {git="https://github.com/AnonComrade993/pixelate.git"}
wasm-bindgen = "0.2.92"
